### ISSUE TITLE
Sugerencia para cambiar "Preguntas Conceptuales" para mentores.

### ISSUE THREAD

**Issue by LunaConstanza** [Laboratoria/job-application-public#10]
En DEV002 proponemos cambiar un poco las [preguntas conceptuales](https://github.com/Laboratoria/job-application-public/blob/main/02-tech-mentoring/interviewer-guide/questions.md) sugeridas a los mentores, principalmente sería quitar las preguntas de Docker, ya que en el proyecto BQ-Api, Docker ya no es utilizado y se les da otra alternativa más acorde a su nivel de aprendizaje y en realidad son muy pocas las que llegan a este proyecto y alcanzan a ver Docker. A cambio de esto, podríamos agregar preguntas sobre Git ya que todas las estudiantes sí tendrían estos conocimientos.

Nuestras preguntas sugeridas para Git serían las siguientes:
- ¿Cuál es la utilidad del comando git log?
- ¿Qué es y para qué sirve un pull request?
- ¿Qué es un conflicto al hacer merge y cómo puedes solucionarlo?
- ¿Cuál es la utilidad de trabajar con ramas en Git?

Y una pregunta extra sobre la terminal
- ¿Cómo puedes navegar entre directorios utilizando la terminal?

Estas sugerencias las levante al equipo de git-camp-planning como recomendó Mariano quien está de acuerdo con quitar las preguntas de Docker, y Alpi junto a Icarito estuvieron de acuerdo en que agregáramos las preguntas de Git (mas una de terminal) por la importancia de saber utilizar el Control de Versiones.

**Comment by merunga** [comment]
ya quedo en
https://github.com/Laboratoria/job-application-public/commit/dd65f8a7016c63242cdc84317add65ea604759b1

Gracias @LunaConstanza por el reporte
